[tool.black]
line-length = 120
target-version = ['py38']

# regex
exclude = '''
/(
  \.git |
  \.mypy_cache |
  \.?venv |
  br-* |
  branch-* |
  plugin/libs |
  tests/files |
  stubs |
  typings
)/
'''
